### ISSUE TITLE
Imported library includes unstable androidx deps

### ISSUE THREAD

**Issue by VitKap** [FunkyMuse/KAHelpers#38]
Hello,

I use viewbinding helper in my project and it is really awesome. In build.gradle I just added `implementation"com.github.FunkyMuse.KAHelpers:viewbinding:2.1.19"`. After some exploration I found out that my module is using the viewbinding module's libraries (eg. [fragment, activity](https://github.com/FunkyMuse/KAHelpers/blob/2975d62c258ab494ae8358d9d3f71a0a6a0a084c/build.gradle#L12-L13), lifecycle deps)

Is there a way how to enforce gradle to use the versions from my module gradle? I use stable versions of androidx in my app and don't want to mix with un-stable. Ofcourse there is a way - just  to copy files somewhere to my project but I am curious about posibilities of gradle.

Thanks

**Comment by FunkyMuse** [comment]
fragment  = "1.3.0-rc01"
activity = "1.2.0-rc01"

Rc is stable, what you mean by unstable?
Also the module has them as implementation not as api hence they're not included into your code and you can use your own stable ones but the module relies on them since it needs their lifecycle awareness

You can disable transitive dependencies by setting 
transitive = false

**Comment by VitKap** [comment]
By unstable I mean that it is not fully stable, maybe unstable is just a wrong expression for it. I don`t want to have Rc libs in production code... Rc is a prospective stable release (according to  [docs](https://developer.android.com/jetpack/androidx/versions)).

Thanks a lot `transitive = false` works very well.
